openapi: 3.0.2
info:
  title: "E-Stock listing stock API"
  description: "Register stock price in stock market"
  version: "0.0.1-SNAPSHOT"
servers:
  - url: "https://localhost:8082"
    description: "Development server"
paths:
  /api/v1.0/market/stock/add/{companyCode}:
    post:
      summary: Add new stock price
      operationId: createStockPrice
      tags:
        - Stock
      parameters:
      - name: companyCode
        in: path
        description: 'Company code needs to be associated with stock price'
        required: true
        schema:
          type: string
      requestBody:
        description: Stockprice payload
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/StockPrice'
      responses:
        '200':
          description: Created stock price succcessfully
          content:
            text/plain:
              schema:
                type: string
  /api/v1.0/market/stock/getall/{companyCode}:
    get:
      summary: Get stock price
      operationId: getAllStockPrice
      tags:
        - Stock
      parameters:
        - name: companyCode
          in: path
          description: 'Company code passed'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Created stock price succcessfully
          content:
            application/json:
            schema:
              type: array
              items:
                type: object
                $ref: '#/components/schemas/StockPrice'
  /api/v1.0/market/stock/delete/{companyCode}:
    delete:
      summary: Delete stock price
      operationId: deleteStockPrice
      tags:
        - Stock
      parameters:
        - name: companyCode
          in: path
          description: 'Company code passed'
          required: true
      responses:
       '200':
         description: Deleted stock price succcessfully
components:
  schemas:
    StockPrice:
      type: object
      required:
        - stockPrice
        - startDate
        - endDate
      properties:
        id:
          type: integer
        stockPrice:
          type: float
        startDate:
          type: string
          format: date
          example: "2021-01-30"
        endDate:
          type: string
          format: date
          example: "2021-01-30"